version: '3'
services:
  proxy:
      image: "jwilder/nginx-proxy:alpine"
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
  client:
    image: "internetofdrums/internet-drum-pattern-queue-client:latest"
    ports:
      - "9000:80"
    environment:
      - VIRTUAL_HOST=internetofdrums.com,www.internetofdrums.com
  service:
    image: "internetofdrums/internet-drum-pattern-queue-service:latest"
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=api.internetofdrums.com
      